apiVersion: migration.openshift.io/v1alpha1
kind: MigCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: my-cluster
  namespace: mig
spec:
  clusterRef:
    name: my-cluster
    namespace: mig
  serviceAccountSecretRef:
    name: my-cluster
    namespace: openshift-config
